# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(27272A)
$foreground = rgb(D3E5ED)
$color0 = rgb(4C4D50)
$color1 = rgb(1A1D28)
$color2 = rgb(1F242F)
$color3 = rgb(2F4E67)
$color4 = rgb(3D5360)
$color5 = rgb(587A8A)
$color6 = rgb(618898)
$color7 = rgb(B8D2DD)
$color8 = rgb(80939A)
$color9 = rgb(232735)
$color10 = rgb(29303E)
$color11 = rgb(3F688A)
$color12 = rgb(526E80)
$color13 = rgb(75A3B8)
$color14 = rgb(81B5CB)
$color15 = rgb(B8D2DD)
