# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D3E5ED
background         #27272A
cursor             #7E8A96

active_tab_foreground     #27272A
active_tab_background     #D3E5ED
inactive_tab_foreground   #D3E5ED
inactive_tab_background   #27272A

active_border_color   #D3E5ED
inactive_border_color #27272A
bell_border_color     #1A1D28

color0      #4C4D50
color1		#1A1D28
color2		#1F242F
color3		#2F4E67
color4		#3D5360
color5		#587A8A
color6		#618898
color7		#B8D2DD
color8		#80939A
color9		#232735
color10		#29303E
color11		#3F688A
color12		#526E80
color13		#75A3B8
color14		#81B5CB
color15		#B8D2DD
