# ============================================
# Hyprland - Main config
# ============================================

# Default apps
$term = kitty
$files = thunar
$browser = xdg-open "https://"
$scriptsDir = $HOME/.config/hypr/scripts

# Source modular configs
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/workspaces.conf
source = $HOME/.config/hypr/env.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/settings.conf
source = $HOME/.config/hypr/decorations.conf
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf
