# ============================================
# Kitty - Terminal emulator
# ============================================

# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

# Window
background_opacity 1
dynamic_background_opacity 1
confirm_os_window_close 0
window_padding_width 4
enable_audio_bell no

# Cursor
cursor_trail 0
cursor_shape beam
cursor_beam_thickness 1.2

# Scrollback
scrollback_lines 2000
wheel_scroll_min_lines 1

# Display server
linux_display_server auto

# Selection
selection_foreground none
selection_background none

# Theme: Tokyonight
foreground #c0caf5
background #1a1b26
cursor #c0caf5

# Keybinds
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text all \x03
